#!/bin/bash
shopt -s nullglob

if [ $# -ne 2 ]; then
    echo "Error: Enter 2 arguments - source directory and target directory." >&2
    exit 1
fi

if [ ! -d "$1" ]; then
    echo "Error: Source directory '$1' does not exist." >&2
    exit 1
fi

if [ ! -d "$2" ]; then
    echo "Error: Target directory "$2" does not exist." >&2
    exit 1
fi

SOURCE=$(realpath "$1")
TARGET=$(realpath "$2")

case "$TARGET" in
    "$SOURCE" | "$SOURCE"/*)
        echo "Error: Target directory cannot be contained within the source directory." >&2
        exit 1
        ;;
esac

FILES=$(find "$SOURCE" -type f | wc -l)
COUNT=0
FAILED=0

sort_photos(){
    local S="$1"
    local DATE YEAR MONTH NAME
    echo "Currently processing directory: $SOURCE"
    echo "-------------------------------------------------"
    for ITEM in "$S"/*; do
        NAME=$(basename "$ITEM")

        # Normal file
        if [ -f "$ITEM" ]; then
            COUNT=$((COUNT + 1))

            # Get date from EXIF
            DATE=$(exiftool -d '%Y/%m' -s3 -DateTimeOriginal "$ITEM" 2>/dev/null) 
            if [ -z "$DATE" ]; then

                # Fallback to modification date from stat
                DATE=$(date -d "@$(stat -c %Y "$ITEM")" '+%Y/%m')
                if [ -z "$DATE" ]; then
                    echo "$COUNT/$FILES Creation date is unavailable for file: $ITEM." >&2
                    FAILED=$((FAILED + 1))
                    continue
                fi

                echo "$COUNT/$FILES files. File $NAME was processed using modification date (no EXIF)."
            else
                if [ $(($COUNT % 5)) -eq 0 ]; then
                    echo "$COUNT/$FILES files processed..."
                fi
            fi

            YEAR=${DATE%/*}
            MONTH=${DATE#*/}

            if mkdir -p "$TARGET/$YEAR/$MONTH" && mv "$ITEM" "$TARGET/$YEAR/$MONTH/$NAME"; then
                :
            else
                echo "[$COUNT/$FILES] File $NAME transfer failed." >&2
                FAILED=$((FAILED + 1))
            fi
        fi

        if [ -d "$ITEM" ]; then
            sort_photos "$ITEM"
        fi
    done
}

sort_photos "$SOURCE"
echo "==================================================="
SUCCESSFUL=$((COUNT - FAILED))
echo "Done! $SUCCESSFUL/$COUNT files successfully moved. Processing of $FAILED files failed."
